### ISSUE TITLE
[4.0] [META] Install from Web Tasks

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#19429]
Meta issue tracking tasks for the Install from Web plugin (style and JavaScript related tasks are in this repo, markup related work goes to https://github.com/joomla-extensions/install-from-web-server):

- [x] Migrate the loading container to use `Joomla.loadingLayer` JavaScript (Complete in #23104)
- [x] jQuery Decoupling
    - Requests (all AJAX GET requests using JSONP)
    - Custom Events (`ajaxStart` and `ajaxStop` which honestly is just the loading layer logic) (Complete in #23104)
    - Animations
        - There is a smooth scroll to top for page navigation
        - When the "Install" button on free extensions is clicked on the single extension view, the main body area is hidden so the confirm box (`#uploadform-web`) is the only part of the tab visible
- [ ] Change `#web-loader-error` element to use alert CE
- [x] Load language strings through `Text::script()` and use corresponding JavaScript
- [ ] Re-implement the `.fader` element
- [ ] Restore the link to the JED category in the breadcrumb element
- [x] Break dependency to global variables (can only apply to 4.0 layouts/script)
- [ ] Bootstrap 5 review

**Comment by C-Lodder** [comment]
Do you want me to handle the JS?

**Comment by brianteeman** [comment]
go for it!!

Migrating it to the core was about my limit ;)

**Comment by brianteeman** [comment]
>  Restore the link to the JED category in the breadcrumb element

Took me ages to find that link :)
Do we really need it?

**Comment by mbabker** [comment]
Probably not, but I used the 3.x layouts as the design guide which has that link.  So for consistency it should either exist for the 4.0 layouts or go away completely.

**Comment by jwaisner** [comment]
bumping for any updates that may be needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19429">issues.joomla.org/tracker/joomla-cms/19429</a>.</sub>

**Comment by mbabker** [comment]
Well considering nobody has touched the plugin code, I would say there is no need for any updates because nothing has been done to warrant an update.

**Comment by wilsonge** [comment]
So I don't see why any of the above would block install from web from functioning?

**Comment by mbabker** [comment]
It functions just fine last I checked (which admittedly was no time this year).  The UI is broken mainly.  In 3.x clicking the install button has a transition effect to show the user an info block and actually do the install or go to the developer's website.  Because all the jQuery stuff (minus ajax) was commented out without immediately replacing the functionality right now clicking that button shows the info block at the bottom of the view without any clue to the user it's there.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/79075554-804e5f00-7ceb-11ea-9152-40cbe7d6e0e2.png)

**Comment by wilsonge** [comment]
But that install doesn’t work either and gives a JS error Joomla.submitButton5 is not defined (which I can’t find a reference to the in the repo here) and only in the plugin directory of the install-from-web repo

**Comment by mbabker** [comment]
I’m pretty sure I renamed the function to something more clear and in the plugin JS class instead of the Joomla object when doing the ES6 rewrite.

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/commit/59ca5aabf26343d1086fdf66809e594de427ddb0#diff-8a5c0e9223fc9e812752777d2be474aaL299

For the life of me I can't work out how that was replaced.

**Comment by richard67** [comment]
Install from web doesn't really work in J4 as of today (2020-05-07). See https://github.com/joomla/joomla-cms/pull/28981#issuecomment-625422620 and comment below it.

- The modal isn't a modal it seems, but still has buttons for a modal.
- When using the install button of the "modal" for a J4 alpha compatible extension (akeeba backup), nothing happens, and the browser console shows: "Uncaught TypeError: Joomla.submitbutton5 is not a function at HTMLInputElement.onclick (index.php?option=com_installer&view=install:349)".

**Comment by richard67** [comment]
Ah I see a few comments above, you know that already.

**Comment by C-Lodder** [comment]
- [x] jQuery decoupling: fixed in https://github.com/joomla/joomla-cms/pull/28981

**Comment by HLeithner** [comment]
@C-Lodder can you help fixing the rest of the tasks?

**Comment by C-Lodder** [comment]
alerts already moved to CE's here: https://github.com/joomla/joomla-cms/pull/28992

> Re-implement the .fader element

No idea what this is, but don't think it's required

> Restore the link to the JED category in the breadcrumb element

Breadcrumb links already take you to the JED category within the web installer.

**Comment by joomdonation** [comment]
Base on comments from @C-Lodder, I think all the tasks in this issue were completed. @richard67 Maybe you can take a look at it and confirm (or someone has experience with install from web can check and make sure it is working as expected). I just tried to use and see that it is working well.

**Comment by brianteeman** [comment]
None of this looks correct

![image](https://user-images.githubusercontent.com/1296369/111025879-f87f4200-83de-11eb-852e-1b6fac8bebb7.png)

**Comment by richard67** [comment]
@brianteeman Could that come from #32422 ? If so, then the look of these fields is something on the big list to be cleaned up, i.e. not specific to the install from web.

Or is it maybe a BS 5 thing? Then it is covered by the last item "Bootstrap 5 review" in the check list in the description.

@joomdonation Unfortunately I'm not deep enough into the install from web to be the one who can sort it out.

**Comment by brianteeman** [comment]
BS5 i think

**Comment by joomdonation** [comment]
Would be great if someone with frontend skill could finish this BS5 task so that we can close this release blocker.

**Comment by richard67** [comment]
Maybe @drmenzelit could have a look on it and check if it needs some adjustments to BS 5 in css or markup?

Or could there be js issues, too, related to BS 5 changes? In this case @dgrammatiko should have a look on it, too.

**Comment by rdeutz** [comment]
Final bits are done in #32851, closing this
