### ISSUE TITLE
[4.0] PLACEHOLDER: Privacy Component does not work

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#24188]
~As of time of writing 14 March 2019 am about to start working on merging 3.9 code into the Joomla 4 branch. Until all of 3.9.0 release is merged in I am going to actively close people refactoring the component onto J4.0 structures or trying to fix styling. This is to make life as simple as possible for merging the rest of the 3.9.0 release in. Once all of Joomla 3.9.0 has been merged into the Joomla 4 branch I will start accepting Pull Requests to start working on the component.~

~Any issues/pull requests related to the component not functioning correctly due to bs2 vs bs4 (or anything else) should be closed and pointed to this issue~

MERGES COMPLETE THE ABOVE PARAGRAPHS NO LONGER APPLIES

## TODO Items
- [x] Clean up all the SQL files in the update folder (we will only support upgrading from 3.10.0 and higher)
- [x] Clean up the asset table entries
- [x] Clean up the lft/rgt values in the menu's table

## Afterwards
- [x] Cleanup the styling
- [ ] A11y audit
- [x] Namespace

**Comment by Hackwar** [comment]
The data from the privacy dashboard has to be moved to modules and then integrated into the users dashboard.

**Comment by wilsonge** [comment]
@brianteeman are we happy with a11y in the component at this point?

**Comment by brianteeman** [comment]
Shouldn't you be asking the accessibility team?
