### ISSUE TITLE
[4.0] META test sample plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25777]
- [x] Add completed step (step9)
- [x] Fix the weird empty message referring to multilingual step 8
- [ ] Update content to remove beez3, beez5, atomic references
- [ ] Add privacy sample content
- [ ] Add field sample content
- [ ] Update module positions used for Cassiopeia
- [ ] Remove references to search component and module
- [ ] loadmoduleid has the wrong module ids in articles
- [ ] modules in position none loaded in articles above are assigned to the wrong menu item
- [ ] Deep Menu doesnt expand
- [ ] Deep Menu - submenu items have the wrong parent - bug in lft rgt values ?
- [x] Update external links to https
- [x] step 4 failing due to maximum execution time of 30 seconds exceeded.

**Comment by Quy** [comment]
> Add field sample content

Same as #14019?

**Comment by brianteeman** [comment]
yes - lets close it there and keep it all in one place

**Comment by brianteeman** [comment]
added more issues

**Comment by brianteeman** [comment]
I had hoped to address these issues in individual PR to make it easier for testing. However thats not going to be possible because of the way the plugin is created. I'm not even sure some of the issues can be resolved eg getting the module id or the menu item id

**Comment by Bakual** [comment]
Regarding bugs in the data. When I created the plugin, I didn't check if content is correct. I just took the existing data and converted it as best as I could. So yes, there can be corrupt data in it.

The IDs of the created items should all be stored in the user session. Of course you can only use the IDs from thing that are already inserted in previous steps. For example it is impossible to link to a menuitem from an article since articles are created before the menuitems are. That's a restriction we have to live with.

**Comment by brianteeman** [comment]
So none of the content items that use {loadmoduleid} can ever be made to work with this plugin as it is currently structured because the articles are created in step 3 & 4 but the modules are not created until step 8 ??

**Comment by Bakual** [comment]
Yep, and the modules can't be created before the articles because they need them.
Except if you want to create the article and update it in a later step again with the correct module ID, that may work.

**Comment by brianteeman** [comment]
Maybe a plan would be to remove all of the articles and menu items that exist just to display the modules (and their associated modules) and if anyone takes the time to work out how to resolve the issue they can be re-added. The last thing we want is for people to use the test data and think that j4 is buggy because the test data is wrong.

?

**Comment by Hackwar** [comment]
I'd rather keep them in and fix them soonish. If you remove them, they will be gone for good.

**Comment by brianteeman** [comment]
Well someone else will have to do that as that time of code is still beyond me ;)

**Comment by Bakual** [comment]
Just removing the {loadmoduleid} and references to menuitems from the articles should be fine. If the article doesn't make sense anymore, it can be deleted.
Honestly I doubt anyone will invest the time needed to fix this as imho it's not worth the effort. Except if you think the testing sample data should cover all possible aspects of the CMS.

**Comment by Hackwar** [comment]
The testing sampledata should not cover **all** aspects, but it should provide a setup for every frontend view of a component, all modules with at least one layout configuration, a bigger setup of com_content with the different possibilities and I'm thinking about adding an option to generate massive amounts of content, like 10k articles.

Creating some code to create that content is not complicated, just creating all that content is timeconsuming.

**Comment by Bakual** [comment]
>  I'm thinking about adding an option to generate massive amounts of content, like 10k articles.

If I remember right, there exists already such an extension.

**Comment by brianteeman** [comment]
Com_overload

**Comment by brianteeman** [comment]
I guess that we can fix the module issue easily now that i think about it by using {loadmodule mod_type,the title,} instead of {loadmoduleid xxx}

**Comment by Bakual** [comment]
Yep, that way it should work fine 👍

**Comment by brianteeman** [comment]
doh - thats the way it is right now. Thats not the problem. The problem is that each of those modules is assigned to only appear on a selected menu item. By the looks of it they are all assigned to one menu item too high.

for example the menu module is assigned to display on the statistics page

![image](https://user-images.githubusercontent.com/1296369/62836323-b10c5f00-bc59-11e9-8c7a-382fb3cc85bb.png)

**Comment by Hackwar** [comment]
Yes, com_overload is there, but as far as I can see, hasn't been touched in a long time. Considering also that the author just recently announced that he does not want to see his code in Joomla, I'm not confident to promote that and rather see if we can role something like that ourselfs.

**Comment by Bakual** [comment]
Make a PR to his repo if it needs to be improved. It doesn't need to be Joomla code.

**Comment by SharkyKZ** [comment]
For point 2 test #27183 please.

**Comment by brianteeman** [comment]
updated to mark 2 as complete

**Comment by Quy** [comment]
Please add step 4 failing due to maximum execution time of 30 seconds exceeded.

https://github.com/joomla/joomla-cms/pull/26392#issuecomment-550546132

**Comment by brianteeman** [comment]
@quy I cannot replicate that

**Comment by Quy** [comment]
Please read this comment. Are you testing on XAMPP with PHP 7.3.9 and 10.4.6-MariaDB?

https://github.com/joomla/joomla-cms/pull/26392#issuecomment-551204748

**Comment by brianteeman** [comment]
updated the list

**Comment by wilsonge** [comment]
Are these now all fixed?

**Comment by brianteeman** [comment]
no one seems remotely interested in it

**Comment by PhilETaylor** [comment]
Maybe no one will be interested in the new 5 issues either... /facepalm
