### ISSUE TITLE
[4.0] Remaining mails to be converted to mail templates

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#29215]
### Steps to reproduce the issue

This is just a reminder on the remaining mail types to be converted to mail templates after PR #28722 has been merged.

### Expected result

All kinds of mails sent by the core are using mail templates.

### Actual result

Done:
- [x] Testmail in global configuration (done with PR #22126 )
- [x] Contact form in com_contact (done with PR #28722 )
- [x] com_contact API controller to send a mail (done with PR #28722 )
- [x] Joomla Updatenotification (done with PR #28722 )
- [x] Massmailer mail (done with PR #28722 )
- [x] Mail to the new user when creating a new user in the backend (done with PR #28722 )
- [x] Password reset for users in frontend (done with PR #28722 )
- [x] Username reminder for users in frontend (done with PR #28722 )

To be done:
- [ ] Notification mail from com_actionlogs (administrator\components\com_actionlogs\src\Model\ActionlogModel.php line 174)
- [ ] com_messages notification (administrator\components\com_messages\src\Model\MessageModel.php line 435)
- [ ] com_privacy send export to user (administrator\components\com_privacy\src\Model\ExportModel.php line 240)
- [ ] com_privacy notification about a new request (administrator\components\com_privacy\src\Model\RequestModel.php line 362)
- [ ] com_privacy creating a new request (components\com_privacy\src\Model\RequestModel.php line 188/190 ATTENTION!! HERE IS A BUG! The mail is send twice!)
- [ ] reminder of expiring privacy consent (plugins\system\privacyconsent\privacyconsent.php line 604)
- [ ] User registration (components\com_users\src\Model\RegistrationModel.php line 198, 254, 650, 711)

**Comment by richard67** [comment]
I'll try to do at least some of the remaining mail templates 'cause I know now how it has to be done.

**Comment by richard67** [comment]
Closing as having a pull-request which implements all missing mail templates listed in the description. Thanks @Hackwar for that work. Unfortunately I won't be able to test due to health problems (nothing serious, only a bit painful). When I'm fit again and it's still necessary I'll test of course.
