### ISSUE TITLE
[4] FTP Layer Release Blocker Issues Summary

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33251]
### Issues

- [ ] [4][FTP Layer] Optionally saving FTP credentials creates impossible file operation scenarios #33304
- [ ] [4][FTP Layer] When FTP Layer enabled, Joomla NEVER caches pages #33249 @PhilETaylor 
- [ ] [4][FTP Layer] Folder Permissions screen incorrect states folders are unwritable. #33245 @PhilETaylor 
- [ ] [4][FTP Layer] Cannot create new template files #33246 @PhilETaylor 
- [ ] [4][FTP Layer] Cannot upload images in Media Manager #33244 @PhilETaylor 
- [ ] [4][FTP Layer][SECURITY] FTP Credentials displayed to the screen in plain text on Upload & update page #33242 @PhilETaylor 
- [ ] [4][FTP Layer] Cannot install extensions at all #33241 @PhilETaylor 
- [ ] [4][FTP Layer] Cannot save template file modifications #33239 @PhilETaylor 
- [ ] [4][FTP Layer] use of is_writable when FTP Layer needed causes false error messages #33238 @PhilETaylor 
- [ ] [4][FTP Layer] Filesystem based Sessions do not work. #33237 @PhilETaylor 
- [ ] FTP doesnt work #33079 @brianteeman
- [x] [4.0] autoload_psr and ftp #33019  @brianteeman
- [ ] [3] ERROR: Wrong FTP host or port #28199 @twister65

### Pull Requests to fix things in FTP Layer

- [x] [4][FTP Layer] JLIB_CLIENT_ERROR_FTP_BAD_RESPONSE #33284 @PhilETaylor 
- [x] [4] Use CMS library which is FTP Layer aware #33283 @PhilETaylor 
- [ ] [4.0] Fix Update Joomla Using FTP #33281 @joomdonation
- [ ] [4.0] FTP error message #33123 @brianteeman
- [ ] [4.0] Re-Implementing FTP-layer during CMS installation #31857
- [ ] [4.0] com_installer FTP #33077 @Hackwar
- [ ] [4] Ensure opcache file invalidate on file copy & delete #32915 (If we change files by FTP, we also need to clear PHP Opcache for those files! ) @PhilETaylor 
- [x] [4] Allow in-memory autoload_psr4.php #33263 @PhilETaylor 

### Pull Requests proposed to REMOVE the FTP layer

 - [4.0] Removing GUI parts of FTP layer #33390
 - [4.0] Remove the FTP Layer #21507

### What needs testing:

This is also an attempt to record all the areas of Joomla 4 that require file write access. 

 - [ ] The writing of autoload_psr4.php namespacemap
 - [ ] All of the issues mentioned in the Summary at https://github.com/joomla/joomla-cms/issues/33251 need checking as to what happens when the FTP Credentials are MISSING from the Joomla Global Config (As saving credentials is optional)
 - [ ] Saving the Joomla Global Config
 - [ ] Creating Template Overrides in Template Manager
 - [ ] Template Manager cannot rename, save or delete files, it says "some features may not work" well the point of the FTP Layer is that they SHOULD work.
 - [ ] Joomla Update restore_finalisation use of `unlink` in AKFactory
 - [ ] Saving modifications to template files
 - [ ] Media Manager file uploads/deletes/renames
 - [ ] Media Manager Image changes (Crop/rotate/scale etc)
 - [ ] Filesystem Caching layer 
 - [ ] Debug Mode toolbar cache files (vendor/maximebf/debugbar) uses file_put_contents
 - [ ] Error logging to file (Joomla logs)
 - [ ] Log Rotation Plugin moving files
 - [ ] UpdateModel.php if FTP Write fails, it then attempts to direct access with file_put_contents
 - [ ] CLI Database export/import
 - [ ] Use of Joomla\Archive package which uses the Joomla\Filesystem and not Joomla\CMS\Filesystem packages.
 - [ ] CLI DaemonApplication use of `unlink` and write on a pidFile
 - [ ] PHPMailer use of the file system when signing emails (Joomla doesn't sign emails, but the feature is exposed so 3pd can)
 - [ ] "Update Structure" button on the Database page (Used to be "fix") cannot run as it deletes files. 
 - [ ] Extension installation from URL says "Unable to detect manifest file." and doesn't prompt for credentials when trying to install.
 - [ ] Extension Upload and Install doesn't work when no FTP credentials stored, not prompted for credentials. 
 - [ ] Languages: Edit Override cannot save the override files, not prompted for credentials, gives bad error message with no actual error message "Save failed with the following error:"

** Warning: This list was compiled before coffee, it is possible its a very incomplete list! ** 

### Docker image 

As promised in https://github.com/joomla/joomla-cms/issues/20774#issuecomment-646082244 I created a FTP Docker image based on the official joomla docker images

 - https://github.com/PhilETaylor/joomla-ftptest

-----

### Leadership devisions/comments on keeping the FTP Layer in Joomla 4.

George, **The Joomla Release Lead for Joomla 4** - [stated on 3rd March 2019](https://github.com/joomla/joomla-cms/pull/21507#issuecomment-469028920) that he believed it **"give or take works"**

<img width="953" alt="Screenshot 2021-04-24 at 15 32 19" src="https://user-images.githubusercontent.com/400092/115962254-580a5a80-a512-11eb-91d6-62f13e5fddf6.png">

George, **The Joomla Release Lead for Joomla 4** - [stated on 1st March 2020](https://github.com/joomla/joomla-cms/pull/28029#issuecomment-593151383) - **"We're keeping it."**

<img width="756" alt="Screenshot 2021-04-24 at 15 19 26" src="https://user-images.githubusercontent.com/400092/115961906-7c653780-a510-11eb-8171-581569b04758.png">

Although [a day later he stated](https://github.com/joomla/joomla-cms/pull/28029#issuecomment-593396872):  **"admittedly I've never tested FTP Modes"**

**Comment by alikon** [comment]
is this a release blocker ?
my usual 0.02

**Comment by PhilETaylor** [comment]
I guess that depends on the decisions those in leadership make. All I can do is make that decision easier for them to take by documenting the issues to show how big of an issue, 3 years later, it still is.

**Comment by PhilETaylor** [comment]
If you mean, should you flag this specific issue with a release blocker tag? - then sure, that would highlight it well.

**Comment by alikon** [comment]
i'd not mark rb , instead some kind of wont fix

**Comment by PhilETaylor** [comment]
Again not my decision to make :) I dont get paid enough. 

If its a `won't fix` then there is also a LOT of work to do to REMOVE the FTP Layer... + documentation + marketing spin

So either way, regardless of the decision, this is blocking ...

**Comment by brianteeman** [comment]
> i'd not mark rb , instead some kind of wont fix

If its a wont fix then you must remove all the useless code

**Comment by alikon** [comment]
iirc there was such pr, anyway ive expressed my personal opinion

**Comment by PhilETaylor** [comment]
> iirc there was such pr,

Yes in 2019 - but it was rejected - history: https://github.com/joomla/joomla-cms/pull/21507

It would need each area revisiting again if the decision to remove FTP Layer was made.

**Comment by jwaisner** [comment]
There is no decision to remove the FTP Layer. It is a Release blocker. Any assistance on fixing it is appreciated.

**Comment by brianteeman** [comment]
Somethings cannot be fixed.
Some things should not be fixed.

**Comment by PhilETaylor** [comment]
I have added Georges comments on keeping the FTP layer from Match 2019 and March 2020 to the opening of this issue

**Comment by richard67** [comment]
Soon I have to go to German technology museum in Munich to be able to find servers for testing it.

**Comment by joomdonation** [comment]
@PhilETaylor Do you know how can I setup FTP layer with permissions issue on a Windows computer for testing these FTP things?

**Comment by PhilETaylor** [comment]
@PhilETaylor Do you know how can I setup FTP layer with permissions issue on a Windows computer for testing these FTP things?

On windows, no sorry, unless you can commit to learning docker/virtual machines. 

A standard Ubuntu server with Apache installed today replicates the problem because apache runs by default as www-user and the files are then owned by root, ubuntu or your FTP server service user. 

I also prepared a docker container of this exact set up as requested by George some time ago - for those who understand docker. https://github.com/PhilETaylor/joomla-ftptest - that takes the [Official Joomla Docker images](https://hub.docker.com/_/joomla) [and installs VSFTP Server](https://github.com/PhilETaylor/joomla-ftptest/blob/444ffcc8702d47f4911cba2be0a33a236332b599/docker/Dockerfile#L4) (and nano text editor) 

> @richard67 Soon I have to go to German technology museum in Munich to be able to find servers for testing it.

See above, note that the  [Official Joomla Docker images](https://hub.docker.com/_/joomla) have the same "conflict of permissions" that the FTP Layer addresses, namely that apache runs as www-data user and files owned by another user cannot be written to, but to get around this the OFFICIAL JOOMLA DOCKER IMAGES [fudge the permissions so that all files are owned by www-data](https://github.com/joomla-docker/docker-joomla/blob/c5683fca8a8351a7fab82135b4a804a602ccfe14/php7.3/apache/Dockerfile#L82) /facepalm/

**Comment by PhilETaylor** [comment]
Following [the projects decision to remove the FTP Layer](https://github.com/joomla/joomla-cms/pull/33390#issuecomment-830000434) from Joomla 4 - this can now be closed.
