### ISSUE TITLE
[4] Empty State's Todo

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33266]
Menu items in need of [new blank state design](https://github.com/joomla/joomla-cms/pull/33264)

- [x] [4.0] Moving reusable parts of blankstate layout to a JLayout #33288 @Bakual Thanks!
- [x] [4] redo the logic behind Empty State Queries. #33471
- [X] [4] Remove disabled and useless buttons on empty state leaving just New #33380

Module Items 

 - [x] [4] Introducing empty state to modules #33472

Menu Items: 

- [x] Banners -> Banners #33269
- [x] Banners -> Clients https://github.com/joomla/joomla-cms/pull/33381 
- [x] Banners -> Tracks https://github.com/joomla/joomla-cms/pull/33381
- [x] Contacts -> Contacts  #33265
- [x] Newsfeeds -> Feeds #33268
- [x] Smart Search -> Index #33489
- [x] Smart Search -> Maps #33491
- [x] Smart Search -> Search Terms https://github.com/joomla/joomla-cms/pull/33495/files
- [x] Tags https://github.com/joomla/joomla-cms/pull/33286
- [x] Users -> User Notes https://github.com/joomla/joomla-cms/pull/33273
- [x] Privacy -> Requests https://github.com/joomla/joomla-cms/pull/33272
- [x] Privacy -> Consents https://github.com/joomla/joomla-cms/pull/33272
- [x] Messaging -> Private Messages  #33274
- [X] Site Modules (If mad enough to delete the 3 default) https://github.com/joomla/joomla-cms/pull/33398
- [X] System -> Clear Cache https://github.com/joomla/joomla-cms/pull/33325 @PhilETaylor 
- [X]  System -> Global Checkin https://github.com/joomla/joomla-cms/pull/33383
- [X] System -> Discover [4] Empty State for System-> Discover #33400
- [X] System -> Warnings #33411
- [X] System -> Content Security Policy  #33416
- [x] System -> Redirects https://github.com/joomla/joomla-cms/pull/33384
- [x] Restyle the Post Installation No Messages page (Blank State Style) #33287
- [x] [4] Empty State for Checking for updates #33474
- [x] Categories #33286
- [x] Banners -> Categories #33286
- [x] Contacts -> Categories #33286
- [x] Users -> User Note Categories #33286
- [x] Newsfeeds -> Categories #33286

# Fields, Field groups.

These cannot be easily done as they require additional context dropdowns on the empty state, which make no sense and is confusing as we dont do this elsewhere.

**Comment by PhilETaylor** [comment]
[4.0] com_contact blank state #33265

**Comment by brianteeman** [comment]
You can remove the following from your list as its impossible not to have a one menu and one menu item
 Menus -> Manage
 Menus -> All Menu Items
 Menus -> Main Menu

**Comment by PhilETaylor** [comment]
Done.

**Comment by brianteeman** [comment]
I would move modules into the second group as the site/admin is a context.
It's also very low priority as every site will have modules published on install.

**Comment by PhilETaylor** [comment]
Done

**Comment by PhilETaylor** [comment]
[4.0] com_newsfeeds blank state #33268

**Comment by PhilETaylor** [comment]
@brianteeman Please quote this issue in your PRs please so I (someone else) doesn't have to go hunting :)

**Comment by PhilETaylor** [comment]
[4.0] com_banners blank state #33269

**Comment by brianteeman** [comment]
You can cross off smart-search -filters and smart-search - content maps as their message already makes sense

**Comment by brianteeman** [comment]
Users - action logs needs a different solution or can be crossed off the list. As long as the actionlog plugin is enabled there will always be a log entry as the act of clearing the log creates a log. To get an empty list the plugin needs to be disabled. In which case you should get a different message about needing to enable the plugin

**Comment by PhilETaylor** [comment]
That is a good example, as well as the redirects page, where an empty state page can and should be explaining why something isn't displayed and how to fix it. For example on the redirects page, where it says that the plug-in is not enabled, that could be explained a lot better and be given a call to action and learn more/help￼

**Comment by PhilETaylor** [comment]
And again on the redirects page, even if the plug-in is enabled, it should not say no matching results, but the empty state should say something like

"all good!, we have not detected any broken urls yet, but if we do we will show them here"￼

**Comment by brianteeman** [comment]
Agreed but its a different solution

**Comment by brianteeman** [comment]
[4.0] com_privacy requests and consents blank state #33272

**Comment by brianteeman** [comment]
4.0] com_users notes blank state #33273

**Comment by brianteeman** [comment]
4.0] com_messages blank state #33274

**Comment by PhilETaylor** [comment]
Categories #33286
  Banners -> Categories #33286
  Contacts -> Categories #33286
  Users -> User Note Categories #33286
  Newsfeeds -> Categories #33286

**Comment by brianteeman** [comment]
Banner clients
banner tracks
#33376

**Comment by brianteeman** [comment]
Site Modules/Administrator Modules can be crossed off as that will never get an empty state

**Comment by PhilETaylor** [comment]
> Site Modules/Administrator Modules can be crossed off as that will never get an empty state

Never for admin - agreef.

Probably not in the real world, bt for Site it is a possibly to remove the three installed by default and get a blank slate of 

<img width="830" alt="Screenshot 2021-04-27 at 18 29 27" src="https://user-images.githubusercontent.com/400092/116285948-9b6cff00-a786-11eb-9ba0-ee5df8def609.png">

**Comment by PhilETaylor** [comment]
Well... all good things come to an end, and with the crossing off of the last item on this list, its time for me to bow out. 

If you dont like what we have achieved, want to change anything or want to revert it all - "PRs welcome" as they say. 

#Close

**Comment by PhilETaylor** [comment]
@bembelimen @joomdonation @brianteeman @richard67 Thank you. Appreciate the speed at which this went from a concept to fully merged (almost)

**Comment by Quy** [comment]
Thank you so much for your hard work!! J4 is better/user friendlier for it.

Can you please look into an issue reported here?
https://github.com/joomla/joomla-cms/pull/33100#issuecomment-831445767

Go to System > Manage > Site Modules
Go to System > Manage > Administrator Modules

TIA

**Comment by PhilETaylor** [comment]
@quy fixed by https://github.com/joomla/joomla-cms/pull/33519 Please test and merge urgently.

**Comment by Kostelano** [comment]
I am not creating a new Issue, because not sure if this is correct.

I noticed that if there is 1 user on the site (in fact, you are an administrator), then by sending a private message, in the modal window we get the "old" message that "no matching results".

As far as I understand, the new blank pages were just an alternative to the old posts.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117350307-1768f480-aeb5-11eb-85f4-721827cb53cf.png)

@PhilETaylor @brianteeman

**Comment by Kostelano** [comment]
Thanks for the answer. I have already verified that these messages only apply to the actual filtering of items. And if the result = 0, then we get all the same message format that nothing was found.

My question is over.
