### ISSUE TITLE
[4.1] TODO list: Duplicate Queries

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34123]
To fix in 4.1

In Joomla Admin:

 - [ ] Edit user - 42 statements were executed, 11 of which were duplicates, 31 unique
 - [ ] Edit Article - 45 statements were executed, 6 of which were duplicates, 39 unique
 - [ ] Site Modules - 36 statements were executed, 2 of which were duplicates, 34 unique
 - [ ] Main Menu - 35 statements were executed, 2 of which were duplicates, 33 unique
 - [ ] Edit Category - 45 statements were executed, 6 of which were duplicates, 39 unique
 - [ ] Edit User Group - 26 statements were executed, 2 of which were duplicates, 24 unique
 - [ ] Edit User Access Level - 28 statements were executed, 2 of which were duplicates, 26 unique
 - [ ] Create new private message - 29 statements were executed, 2 of which were duplicates, 27 unique
 - [ ] Post-installation Messages for Joomla CMS - 30 statements were executed, 6 of which were duplicates, 24 unique
